service_type: FilterJointTrajectory
filter_chain:
  -
    name: numerical_differentiation
    type: NumericalDifferentiationSplineSmootherFilterJointTrajectory
  -
    name: linear_spline_velocity_scaler
    type: LinearSplineVelocityScalerFilterJointTrajectory
